fix: add command, test, config/readme housekeeping
salesforcecli/plugin-trust pull request #1
Opened 2020-11-17 23:03 UTC by WillieRuemmele

### What does this PR do?

### What issues does this PR fix or reference?

2020-11-17 23:39 UTC, amphro requested changes

2020-11-17 23:39 UTC, amphro commented on messages/verify.json
> +  "description": "for an npm package validate the associated digital signature if it exits",
This might have been what it was before but it reads really weird to me. Can we say `validate a digital signature for a npm package`?

2020-11-17 23:39 UTC, amphro commented on package.json
> +        "description": "commands to verify the authenticity of a plugin",
This is not the description for the plugins topic. Remove, it is defined elsewhere.

2020-11-17 23:39 UTC, amphro commented on test/.eslintrc.js
> +    'no-console': 'off',
Why is this here?

2020-11-18 20:51 UTC, amphro approved these changes

2020-11-18 20:51 UTC, amphro commented on package.json
> +        "description": "validate a digital signature for a npm package",
This is still not a valid description for `plugins`

2020-11-18 21:09 UTC, shetzel approved these changes

2020-11-18 22:25 UTC, merged